### ISSUE TITLE
sbt build

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#20]
Discuss the ongoing work with the sbt build and publishing to Maven Central...

**Comment by benjchristensen** [comment]
Go to https://bintray.com/reactivex/RxJava/RxScala/view/central

Click on Maven Central and see the errors:

```
Last Sync Status: Validation Failed
Last Sync Errors: Invalid POM: /io/reactivex/rxscala_2.10/1.0.0-RC1/rxscala_2.10-1.0.0-RC1.pom: Project URL missing, SCM URL missing, Developer information missing
Invalid POM: /io/reactivex/rxscala_2.11/1.0.0-RC1/rxscala_2.11-1.0.0-RC1.pom: Project URL missing, SCM URL missing, Developer information missing
Missing Signature: '/io/reactivex/rxscala_2.10/1.0.0-RC1/rxscala_2.10-1.0.0-RC1-javadoc.jar.asc' does not exist for 'rxscala_2.10-1.0.0-RC1-javadoc.jar'.
Missing Signature: '/io/reactivex/rxscala_2.10/1.0.0-RC1/rxscala_2.10-1.0.0-RC1.pom.asc' does not exist for 'rxscala_2.10-1.0.0-RC1.pom'.
Missing Signature: '/io/reactivex/rxscala_2.10/1.0.0-RC1/rxscala_2.10-1.0.0-RC1-sources.jar.asc' does not exist for 'rxscala_2.10-1.0.0-RC1-sources.jar'.
Missing Signature: '/io/reactivex/rxscala_2.10/1.0.0-RC1/rxscala_2.10-1.0.0-RC1.jar.asc' does not exist for 'rxscala_2.10-1.0.0-RC1.jar'.
Missing Signature: '/io/reactivex/rxscala_2.11/1.0.0-RC1/rxscala_2.11-1.0.0-RC1-javadoc.jar.asc' does not exist for 'rxscala_2.11-1.0.0-RC1-javadoc.jar'.
Missing Signature: '/io/reactivex/rxscala_2.11/1.0.0-RC1/rxscala_2.11-1.0.0-RC1.pom.asc' does not exist for 'rxscala_2.11-1.0.0-RC1.pom'.
Missing Signature: '/io/reactivex/rxscala_2.11/1.0.0-RC1/rxscala_2.11-1.0.0-RC1-sources.jar.asc' does not exist for 'rxscala_2.11-1.0.0-RC1-sources.jar'.
Missing Signature: '/io/reactivex/rxscala_2.11/1.0.0-RC1/rxscala_2.11-1.0.0-RC1.jar.asc' does not exist for 'rxscala_2.11-1.0.0-RC1.jar'.
Dropping existing partial staging repository.
```

**Comment by jmhofer** [comment]
This means adding sbt-pgp as well as some "pomExtra".

**Comment by jmhofer** [comment]
A lot of helpful details for this: http://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci

**Comment by benjchristensen** [comment]
Do you need the PGP keys in the Travis file for this?

**Comment by benjchristensen** [comment]
I just added PGP_ENCRYPTION_PASSWORD to the .travis.yml file

**Comment by benjchristensen** [comment]
I need to figure out which of the GPG files I need to provide and how. This was all done in the Jenkins build before on the Gradle plugin. Need to relearn this stuff ...

**Comment by samuelgruetter** [comment]
Is it intended that there's already a [1.0.0-RC1](https://bintray.com/reactivex/RxJava/RxScala/1.0.0-RC1/view)? Imho RxScala should still be at 0.x.y.

**Comment by benjchristensen** [comment]
That's up to you all. Whatever version you want.

**Comment by jmhofer** [comment]
@benjchristensen Do you have the encrypted key files (`secring.gpg.enc` and `pubring.gpg.enc`)? These have to be added to the project.

**Comment by jmhofer** [comment]
If what you added is the password which the key files are encrypted with, and your key also has a passphrase, we also need that passphrase in the `.travis.yml`.

**Comment by jmhofer** [comment]
Everything should be prepared now for proper publishing to Maven. We just need to get the keys working.

**Comment by benjchristensen** [comment]
I have added the files using the travis encrypt-file mechanism:

```
travis encrypt-file pubring.gpg --add
travis encrypt-file secring.gpg --add
```

Travis will take care of decrypting those files. 

The PGP_ENCRYPTION_PASSWORD is the passphrase for the key.

**Comment by benjchristensen** [comment]
Confusingly those files are failing to be decrypted ... even though they were encrypted using Travis.

https://travis-ci.org/ReactiveX/RxScala/jobs/36436024

**Comment by benjchristensen** [comment]
Alright, finally have it working.

When adding two files you can't allow Travis to auto generate the keys, as it creates new keys for each file and overwrites the ones generated for the previous file :-$

The private and public keys are now being decrypted correctly and you can make changes to use them.

Then you can release with whatever version you want ... perhaps 0.21.0 until everyone agrees on moving to 1.0.0-RC1?

**Comment by benjchristensen** [comment]
Here is the log showing the 2 files being decrypted: https://travis-ci.org/ReactiveX/RxScala/jobs/36438163#L35

**Comment by jmhofer** [comment]
Ok, I'll try to release a 0.21.0. But then, you probably should unpublish 1.0.0-RC1 again.

**Comment by jmhofer** [comment]
For some reason, Bintray returned a "405 Not Allowed" when uploading the 2.11 version of RxScala. Maybe because it was in parallel to uploading 2.10? - Then I'll have to do the crosspublishing in the build instead of letting Travis do it...

**Comment by benjchristensen** [comment]
The files released are invalid. 

https://bintray.com/reactivex/RxJava/RxScala/0.21.0/view/central

**Comment by jmhofer** [comment]
The 2.11 was not completely published. - But I can't see the Maven Central stuff on Bintray.
The build for 0.21.1 was completely successful. Maybe this one will get through to Maven? - If not, please paste the error log here again.

**Comment by benjchristensen** [comment]
Looks like it published and is on its way.

**Comment by jmhofer** [comment]
Yay, finally!

**Comment by benjchristensen** [comment]
You can them on the repo now: http://repo1.maven.org/maven2/io/reactivex/

**Comment by samuelgruetter** [comment]
Now that https://github.com/ReactiveX/RxScala/pull/21 is also fine, we can consider this issue resolved, imho :)

**Comment by jmhofer** [comment]
I wonder what happened to the Travis build now. All current PRs have a problem with the keys in the `before_install` script. None of the PRs change anything in the build or configuration. 

Anyone have any idea what's happening here?

**Comment by benjchristensen** [comment]
I know that pull request builds don't allow secure data in them: http://docs.travis-ci.com/user/pull-requests/

So I'm trying to find out how to make it so it doesn't execute that on a pull request.

**Comment by jmhofer** [comment]
Ok, so maybe we can simply move these from before_install into the `publishViaTravis` shell script.

**Comment by benjchristensen** [comment]
Maybe we can move the `openssl` commands inside the `./publishViaTravis.sh` script inside the `if` block? The environment variables will be available to `./publishViaTravis.sh` so the following should work there as well:

```
- openssl aes-256-cbc -K $encrypted_506de5234d8d_key -iv $encrypted_506de5234d8d_iv
  -in key.private.F984A085.asc.enc -out key.private.F984A085.asc -d
- openssl aes-256-cbc -K $encrypted_506de5234d8d_key -iv $encrypted_506de5234d8d_iv
  -in key.public.F984A085.asc.enc -out key.public.F984A085.asc -d
```

Then we just won't have a `before_install` section of `.travis.yml`

**Comment by benjchristensen** [comment]
Yes, I just tried making those changes. It should fix the pull requests, no idea if the publish script will work until next time you try a release.

**Comment by samuelgruetter** [comment]
A few minutes ago, I triggered a rebuild for [build 37](https://travis-ci.org/ReactiveX/RxScala/builds/36759001) (PR https://github.com/ReactiveX/RxScala/pull/23), but it still fails with the same error...

**Comment by samuelgruetter** [comment]
If I do locally

```
git fetch ReactiveX +refs/pull/23/merge
git checkout FETCH_HEAD
```

and then

```
git log --oneline
```

then I can see your two commits:

```
a9c96b7 Update publishViaTravis.sh
3dcf4a5 Remove before_install
```

So it looks like Travis got your updates. But it still executes the openssl commands, which is a contradiction -- I don't get it...

**Comment by benjchristensen** [comment]
Your .travis.yml file is still the old one.

**Comment by zsxwing** [comment]
Close as the build script works well now.
